# Generated by Django 5.1.2 on 2024-10-30 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menu',
            new_name='CategoryModel',
        ),
    ]
