# Generated by Django 5.1.2 on 2024-10-31 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_rename_menu_categorymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_year', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('horsepower', models.IntegerField()),
                ('transmission', models.CharField(max_length=20)),
                ('price_type', models.CharField(choices=[("so'm", "so'm"), ('$', '$')], default="so'm", max_length=10)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='cars/')),
            ],
            options={
                'verbose_name': 'Mashina',
                'verbose_name_plural': 'Mashinalar',
                'db_table': 'Mashina',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='CategoryModel',
        ),
    ]
