# Generated by Django 5.1.2 on 2024-10-31 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_carmodel_delete_categorymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='horsepower',
            field=models.IntegerField(verbose_name='Ot kuchi'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='mileage',
            field=models.IntegerField(verbose_name='Kilometiri'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='model_year',
            field=models.IntegerField(verbose_name='Yili'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='transmission',
            field=models.CharField(choices=[('AT', 'Avtomatik'), ('MX', 'Mexanik')], default='Mexanik', max_length=20),
        ),
    ]
