# Generated by Django 5.1.2 on 2024-10-31 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_carmodel_horsepower_alter_carmodel_mileage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='description',
        ),
        migrations.AddField(
            model_name='carmodel',
            name='body',
            field=models.TextField(default=1, verbose_name="Ma'lumoti"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='image',
            field=models.ImageField(upload_to='cars/images', verbose_name='Rasmi'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='price',
            field=models.IntegerField(verbose_name='Narxi'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='transmission',
            field=models.CharField(choices=[('AT', 'Avtomatik'), ('MX', 'Mexanik')], default='Mexanik', max_length=20, verbose_name='Transmissiyasi'),
        ),
    ]
