# Generated by Django 5.1.2 on 2024-10-31 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_remove_carmodel_description_carmodel_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='transmission',
            field=models.CharField(choices=[('Avtomat', 'Avtomatik'), ('Mexanik', 'Mexanik')], default='Mexanik', max_length=20, verbose_name='Transmissiyasi'),
        ),
    ]
