# Generated by Django 5.1.2 on 2024-10-31 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_carmodel_transmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='transmission',
            field=models.CharField(choices=[('AT', 'Avtomatik'), ('MX', 'Mexanik')], default='Mexanik', max_length=20, verbose_name='Transmissiyasi'),
        ),
    ]
