# Generated by Django 5.0.7 on 2024-11-02 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_alter_carmodel_transmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Kategoriya nomi')),
            ],
            options={
                'verbose_name': 'Kategoriyalar',
                'verbose_name_plural': 'Kategoriyalar',
                'db_table': 'Categories',
                'managed': True,
            },
        ),
    ]
