# Generated by Django 5.0.7 on 2024-11-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_comment_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ism')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Xabar')),
            ],
            options={
                'verbose_name': 'Aloqa',
                'verbose_name_plural': 'Aloqalar',
                'db_table': 'Contact',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
